// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
using System;
namespace DRJ.Utilities
{
	public class Information 
{
     	public static DateTime BuildDate = DateTime.Parse("02/06/2016 12:22:46");

    }
}
