// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
using System;
namespace DRJ.Utilities
{
	public class Information 
{
     	public static DateTime BuildDate = DateTime.Parse("20/05/2016 11:52:24");

    }
}
