// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("1.0.0.12442")]
[assembly: AssemblyFileVersion("1.0.0.12442")]
